---
title: "Viz part 1"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)
```

---set the size and scale of plots in md shown up 

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

Get the data for plotting today.

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2023-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

This results in a dataframe with `r nrow(weather_df)` obervations on six variables

## Same plot from last time

```{r}
weather_df |> 
  ggplot(aes(x=tmin, y=tmax, color=name)) +
  geom_point(alpha=0.5)+
  labs(
    title = "Temperature plot",
    x= "Min daily temp (Degrees C)",
    y= "Max daily temp (Degrees C)",
    color = "location",
    caption = "Max vs min daily temp in three locations; data from moaaa"
  )+ #updating lables
  scale_x_continuous(
    breaks =c(-15,0,15),
    labels = c("-15 C", "0", "15")
  ) +
    scale_y_continuous(
      position = "right",
      trans = "sqrt", #square transformations
      limits = c(20,30) #here not updating x aixs, but if we filter at start, then x axis is also updating with y in(20,30)
  )
```

what about color...
```{r}
weather_df |> 
  ggplot(aes(x=tmin, y=tmax, color=name)) +
  geom_point(alpha=0.5)+
  labs(
    title = "Temperature plot",
    x= "Min daily temp (Degrees C)",
    y= "Max daily temp (Degrees C)",
    color = "location",
    caption = "Max vs min daily temp in three locations; data from moaaa"
  )+
 viridis::scale_color_viridis(discrete = TRUE)
  #use  viridis color package generally is better
```

## Themes

```{r}
weather_df |> 
  ggplot(aes(x=tmin, y=tmax, color=name)) +
  geom_point(alpha=0.5)+
  labs(
    title = "Temperature plot",
    x= "Min daily temp (Degrees C)",
    y= "Max daily temp (Degrees C)",
    color = "location",
    caption = "Max vs min daily temp in three locations; data from moaaa"
  )+
 viridis::scale_color_viridis(discrete = TRUE) +
  theme_bw()+ #black white background;this is reset everything of theme, so put it in front of other theme instructions;theme_classi---removing grids;theme_minimal---b&w without boxline at the outside
  theme(legend.position = "bottom") #moving notations to bottom
```

## data argument...
```{r}
weather_df |> 
  ggplot(aes(x=date, y=tmax, color=name)) +
  geom_point()+
  geom_smooth()

nyc_weather_df=
  weather_df |> 
  filter(name == "CentralPark_NY")

hawaii_weather_df=
  weather_df |> 
  filter(name == "Molokai_HI")

ggplot(nyc_weather_df,aes(x=date, y=tmax,color=name))+
  geom_point()+
  geom_line(data=hawaii_weather_df)
```


## `patchwork`

```{r}
weather_df |> 
  ggplot(aes(x=date, y=tmax, color=name)) +
  geom_point()+
  facet_grid(.~ name) #. no faceting on the rows, name faceting on the columns
```



```{r}
ggp_temp_scatter =
  weather_df |> 
  ggplot(aes(x=tmin, y=tmax, color=name)) +
  geom_point(alpha=0.5)+
  theme(legend.position = "none") #no notations; if bottom,put on bottom


ggp_prcp_density =
  weather_df |> 
  filter(prcp > 25) |> 
  ggplot(aes(x=prcp, fill=name))+
  geom_density(alpha = 0.5)+
  theme(legend.position = "bottom")

ggp_tmax_date=
  weather_df |> 
  ggplot(aes(x=date, y=tmax, color=name)) +
  geom_point()+
  geom_smooth(se = FALSE)+
  theme(legend.position = "bottom")
  

(ggp_temp_scatter + ggp_prcp_density)/ggp_tmax_date # through patchwork package, put plots together
```


## data manipulation

```{r}
weather_df |> 
  mutate(
    name= fct_relevel(name,c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))
  ) |> #reorder x axis in this order
  ggplot(aes(x=name, y=tmax))+
  geom_boxplot()

weather_df |> 
  mutate(
    name = fct_reorder(name, tmax)
  ) |> #reoder in tmax average order
    ggplot(aes(x=name, y=tmax,color=name))+
    geom_violin()
```

## complicate FAS plot

```{r}
litters_df =
  read_csv("data/FAS_litters.csv") |> 
  janitor::clean_names() |> 
  separate(group, into= c("dose", "day_of_tx"),sep=3)

pups_df=
  read.csv("data/FAS_pups.csv") |> 
    janitor::clean_names() 

fas_df=
  left_join(pups_df, litters_df, by = "litter_number")

fas_df |> 
 select(dose, day_of_tx, starts_with ("pd")) |> 
 pivot_longer(
   pd_ears:pd_walk,
   names_to = "outcome",
   values_to = "pn_day"
 ) |> 
  drop_na() |> 
  mutate(outcome= fct_reorder(outcome, pn_day)) |> 
  ggplot(aes(x=dose, y=pn_day)) +
  geom_violin() +
  facet_grid(day_of_tx ~ outcome)
```


